import React,{useEffect,useState} from 'react';
import {fitTone,fitPercent,fitBreakdown} from './fitLogic.js';
import './fit.css';

export default function FitPanel({application,api,onClose}){
 const [data,setData]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{let alive=true;api.get('/applications/'+application.id+'/fit/').then(r=>{if(alive)setData(r.data)}).catch(()=>{if(alive)setError('Fit analysis could not be loaded. Add a job description and try again.')}).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[application.id,api]);
 if(loading)return <div className="fit-panel"><div className="fit-loading">Calculating application fit…</div></div>;
 if(error)return <div className="fit-panel"><div className="fit-head"><div><span className="eyebrow">FIT ANALYSIS</span><h3>{application.role}</h3></div><button className="icon-button" onClick={onClose}>×</button></div><div className="alert error">{error}</div></div>;
 const score=fitPercent(data?.score);return <div className="fit-panel"><div className="fit-head"><div><span className="eyebrow">FIT ANALYSIS</span><h3>{application.role}</h3><p>{application.company}</p></div><button className="icon-button" onClick={onClose}>×</button></div><div className="fit-score"><div className="score-ring" style={{'--score':score}}><strong>{score}</strong><span>/100</span></div><div><span className="eyebrow">APPLICATION FIT</span><h4>{fitTone(score)}</h4><p>Based on the profile and job description stored for this application.</p></div></div><div className="fit-grid">{fitBreakdown(data).map(item=><div className="fit-card" key={item.label}><span>{item.label}</span><strong>{item.value}</strong><small>{item.detail}</small></div>)}</div><div className="fit-columns"><section><h4>Matched skills</h4><div className="skill-list">{(data?.required_matches||[]).map(x=><span className="skill good" key={x}>{x}</span>)}{(data?.preferred_matches||[]).map(x=><span className="skill" key={'p-'+x}>{x}</span>)}</div></section><section><h4>Skill gaps</h4><div className="skill-list">{(data?.required_gaps||[]).map(x=><span className="skill gap" key={x}>{x}</span>)}{!data?.required_gaps?.length&&<p className="muted">No required skill gaps identified.</p>}</div></section></div><section className="fit-recommendations"><h4>Recommendations</h4><ul>{(data?.recommendations||[]).map((x,i)=><li key={i}>{x}</li>)}</ul></section></div>;
}
