# Generated by Django 6.1 on 2026-09-28 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('phone', 'Phone Screen'), ('technical', 'Technical'), ('behavioral', 'Behavioral'), ('system_design', 'System Design'), ('panel', 'Panel'), ('final', 'Final Round'), ('other', 'Other')], default='phone', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('scheduled', 'Scheduled')], default='pending', max_length=20)),
                ('interviewer_name', models.CharField(blank=True, max_length=200)),
                ('interviewer_title', models.CharField(blank=True, max_length=200)),
                ('feedback', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.jobapplication')),
            ],
            options={
                'ordering': ['scheduled_date'],
                'indexes': [models.Index(fields=['application', 'outcome'], name='jobs_interview_application_4f9d5d_idx'), models.Index(fields=['scheduled_date'], name='jobs_interview_schedul_9b7f64_idx')],
            },
        ),
    ]
