import React,{useMemo,useState} from 'react';
import {LIFECYCLE_LABELS,TERMINAL_STATUSES,nextFollowUp,transitionOptions} from './lifecycleLogic.js';
import './lifecycle.css';

export default function LifecyclePanel({application,api,onChanged,onClose}){
 const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [note,setNote]=useState('');
 const options=useMemo(()=>transitionOptions(application.status),[application.status]);
 const move=async status=>{setBusy(true);setError('');try{const payload={status};const follow=nextFollowUp(status);if(follow)Object.assign(payload,{next_action_date:follow,next_action:'Follow up on application'});if(TERMINAL_STATUSES.includes(status))Object.assign(payload,{next_action:'',next_action_date:null});await api.patch('/applications/'+application.id+'/',payload);if(onChanged)await onChanged();}catch(e){setError('Could not update this application. Try again.')}finally{setBusy(false)}};
 return <div className="lifecycle-panel"><div className="lifecycle-summary"><div><span className="eyebrow">APPLICATION LIFECYCLE</span><h3>{application.role}</h3><p>{application.company}{application.location?' · '+application.location:''}</p></div><button className="icon-button" onClick={onClose}>×</button></div><div className="lifecycle-current"><span className="badge" data-status={application.status}>{LIFECYCLE_LABELS[application.status]}</span><span>{application.next_action_date?'Next follow-up: '+application.next_action_date:'No follow-up scheduled'}</span></div>{error&&<div className="alert error">{error}</div>}<label className="lifecycle-note">Transition note<textarea rows="3" value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional reason or recruiter update…"/></label><div className="lifecycle-actions">{options.map(option=><button key={option.status} disabled={busy} className={option.terminal?'danger-button':'secondary'} onClick={()=>move(option.status)}>{option.label}</button>)}</div><div className="lifecycle-timeline"><div className="timeline-line"/><div className="timeline-item"><span className="timeline-dot"/><div><strong>Current stage</strong><p>{LIFECYCLE_LABELS[application.status]}</p></div></div><div className="timeline-item"><span className="timeline-dot"/><div><strong>Next action</strong><p>{application.next_action||'Choose a transition to schedule the next step.'}</p></div></div></div></div>;
}
